version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm i --legacy-peer-deps
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - .npm/**/*
      rewritesAndRedirects:
        - source: "</^((?!\\.).)*$/>"
          target: /index.html
          status: 200
    appRoot: client
